### ISSUE TITLE
Truncate File Action

### ISSUE THREAD

**Issue by qiyuangong** [Intel-bigdata/SSM#1114]
* -file: file Path
* -length: final length

Truncate a given file into given length. References:
* dfsClient.truncate
* DistrubtedFileSystem.truncate

**Comment by qiyuangong** [comment]
@duzhen1996

**Comment by duzhen1996** [comment]
easy task : )

**Comment by qiyuangong** [comment]
Already done. Thanks @huafengw and @duzhen1996.
