### ISSUE TITLE
The detail link of cmdlet redirects to the wrong page

### ISSUE THREAD

**Issue by huafengw** [Intel-bigdata/SSM#1141]
<img width="728" alt="2017-09-22 2 28 20" src="https://user-images.githubusercontent.com/5011399/30731860-7142e1bc-9fa2-11e7-8548-2ddef1eae726.png">

Click the ID of cmdlet does not redirect to the detail page of cmdlet.

**Comment by qiyuangong** [comment]
Already done. Issue closed.
Thanks @zhiqiangx .
