### ISSUE TITLE
1.1.0 (ADAS) - FEATURE (low) Can we clone a rule as a template and then modify?

### ISSUE THREAD

**Issue by aurorahunter** [Intel-bigdata/SSM#1196]
Rather than typing a new rule everytime, it will be easier if we can just modify a template and get started

**Comment by littlezhou** [comment]
Great idea! @zhiqiangx Maybe we can solve it in the following way: in "Smart Notebook" page, mouse click the rule in the 'Rule List' then the rule text will be copied to 'Add Rule' edit box, then it can be edited or re-submitted.

**Comment by aurorahunter** [comment]
Awesome, thanks
