### ISSUE TITLE
1.1.0 (ADAS) - BUG -  HIGH - Where are the logs? In a system with no smart agent running?

### ISSUE THREAD

**Issue by aurorahunter** [Intel-bigdata/SSM#1199]
Whenever an rule is triggered or an action is executed , kindly provide a log file to see if the action completed or not.
We need log files to understand what went wrong and for debugging purpose

**Comment by littlezhou** [comment]
If the there are no smart agents in the system, then all the actions are executed by ssm server, so the log file is logs/SmartServer.log.
