### ISSUE TITLE
1.1.0 (ADAS) - FEATURE (high)  - can we have better ID for cmdlets to more easily find them when we do “ps – ef”  

### ISSUE THREAD

**Issue by aurorahunter** [Intel-bigdata/SSM#1201]
perhaps something that says “SSM” + [“rule-id” or prefix of rule name ] + id
something is that not plain numbers and somewhat unique so we can find it faster in log files

**Comment by qiyuangong** [comment]
Hi @aurorahunter.
I fully understand your comment in this issue, and we are refining our logs related to cmdlet. But, I feel confused about this title. Do you means that each cmdlet can be seen from `ps -ef`?

**Comment by aurorahunter** [comment]
OKay, this is what I mean. 
Today cmdlet IDs are integers like 1, 2, 3, 4, etc, incremental integers.
If I were to look up at a particular cmdlets execution status, it is very hard to grep for numbers "1" as it returns thousands of lines matching "1".

Can we use some Alphanumeric values as Cmdlets IDs so we can search and grep for a particular cmdlets log details.

Let me know if you still have questions.
Appreciate your help

Thanks

**Comment by qiyuangong** [comment]
Already done. Now all logs related to cmdlets have been refined, such that we can grep these logs from log file. Thanks @duzhen1996 

Issue closed.
