### ISSUE TITLE
1.1.0 (ADAS) - BUG (high) MySQL databases showed 800 cmdlets and only 20 processes there .. some actions may have executed and then  rule was stopped

### ISSUE THREAD

**Issue by aurorahunter** [Intel-bigdata/SSM#1203]
BUG (high) MySQL databases showed 800 cmdlets and only 20 processes there .. some actions may have executed and then  rule was stopped
Question – what is the expected behavior on server restart?
As of today, it doesn't seem very consistent

**Comment by littlezhou** [comment]
In trunk the issue has been fixed, it behaviors in the following way: all the pending cmdlets of that rule will be dropped.
