### ISSUE TITLE
1.1.0 (ADAS) -BUGS (high) Stale actions are still visible in dashboard

### ISSUE THREAD

**Issue by aurorahunter** [Intel-bigdata/SSM#1207]
I have restarted the server several times, but stale 20 items just stay on till I add 20 new items.
This is again confusing, maybe once a server is shutdown/restarted, old data must be flushed out or handled in a different way?
![image](https://user-images.githubusercontent.com/26469547/31102810-a0aabd9c-a788-11e7-9776-2f9376d3c988.png)

**Comment by littlezhou** [comment]
@qiyuangong Please check and fix this issue, thanks!

**Comment by qiyuangong** [comment]
Already done. Issue closed. Currently, SSM will mark stale cmdlets and actions as failed. Note that if these cmdlets and actions are trigger by rules, they may be re-submitted.
