### ISSUE TITLE
1.1.0(ADAS) Zero byte files are not processed by SSM

### ISSUE THREAD

**Issue by aurorahunter** [Intel-bigdata/SSM#1217]
Hi,

I'm not sure if this is by design or not, but lets say I have two files:
* /tmp/notes.txt - this file is 10Kb
* /tmp/3.xml  - this is an empty file 

If I do checkstorage/move/ or any action from gui, I do not see any response from the SSM, result is empty.
I believe for some reason SSM does not process 0 byte files. 
Attaching snapshot to prove the same.

![image](https://user-images.githubusercontent.com/26469547/31368058-2f6ef5aa-ad30-11e7-8074-59646c7b4786.png)

![image](https://user-images.githubusercontent.com/26469547/31368067-3d09f124-ad30-11e7-84b6-4fb299b88f24.png)

If you look at the results, SSM says "true" and "successful" although I don't believe the 0 byte files were processed.

Please feel free to add comments/questions/

Thanks
Varsha

**Comment by littlezhou** [comment]
@aurorahunter Checkstorage/move action do process the 0 byte file. For checkstorage action, as there are no blocks for the file, so there is no result output.  For move action, it has no result output at all, no matter the file length.

**Comment by aurorahunter** [comment]
Hi, 
Thanks for getting back on this, but it is very misleading as there isn't any result/output shown.
Can we maybe get some sort of message or something so we know that operation indeed happen?

**Comment by littlezhou** [comment]
Ok, We'll fix it soon.
