### ISSUE TITLE
Low performance in sync(copy) stress test

### ISSUE THREAD

**Issue by duzhen1996** [Intel-bigdata/SSM#1309]
I set the rule like `file:path matches "/test/1MB/*" | sync -dest hdfs://sr518:9000/test`, and write 50000 1MB files into dictionary named "/test/1MB/*". I don't find any evidences proving that there has any wrong in the logic of copy Scheduler, but it takes much more time than mover action and even causes a `MAX connection error` in `wait_for_cmdlet` when I running python script for integration test.

**Comment by duzhen1996** [comment]
I think many http connection is blocked in `wait_for_cmdlet` because of the action is blocked in 'PENDING' status. So this error happend.
```
def wait_for_cmdlet(cid, period=300):
    """
    wait at most 300 seconds for cmdlet to be done
    """
    timeout = time.time() + period
    while True:
        cmdlet = get_cmdlet(cid)
        if cmdlet['state'] == "PENDING" or cmdlet['state'] == "EXECUTING":
            time.sleep(1)
        elif cmdlet['state'] == "DONE" or cmdlet['state'] == "FAILED":
            return cmdlet
        if time.time() >= timeout:
            return None
```

**Comment by qiyuangong** [comment]
@tianlong12 
Please re-test it with newest trunk, we just solve the listing problem in previous version.
