### ISSUE TITLE
Fix 404 after logout 

### ISSUE THREAD

**Issue by littlezhou** [Intel-bigdata/SSM#1368]

**Comment by littlezhou** [comment]
![screenshot from 2017-11-08 13-21-14](https://user-images.githubusercontent.com/10972684/32532734-4c587e5c-c487-11e7-8a8a-12dd476995de.png)

**Comment by zhiqiangx** [comment]
Please try to rebuild with -Pweb.

**Comment by littlezhou** [comment]
The option was already been used, but we (not only me) still have the problem.

**Comment by littlezhou** [comment]
Done!
