### ISSUE TITLE
Suggest change the TiDB DB name from "test" to something like "ssm-meta-store"

### ISSUE THREAD

**Issue by ChenSammi** [Intel-bigdata/SSM#1386]
Currently it's test,  not perfect.  Also password should not be empty.
<properties>
     <entry key="url">jdbc:mysql://127.0.0.1:4000/test</entry>
     <entry key="username">root</entry>
     <entry key="password"></entry>
     ......
 <properties>

**Comment by PHILO-HE** [comment]
This issue has been solved.
