### ISSUE TITLE
Scheduler keeps scheduling same files over although file has been moved to ES and truncate to 0

### ISSUE THREAD

**Issue by aurorahunter** [Intel-bigdata/SSM#1621]
Have shared logs with Qiyang. 
If a rule is scheduled to move a file to S3 filesystem and the file size is truncated to 0, the same file gets scheduled again to be copied over. This should not happen. and showstopper for our ADAS.

**Comment by qiyuangong** [comment]
Hi @aurorahunter . We have fixed this issue on release 1.3.2 and trunk. You can test it in your environment. :)

**Comment by qiyuangong** [comment]
Issue closed. Free free to re-open it if there is any problem.
