### ISSUE TITLE
SSM binary and configure distribution script

### ISSUE THREAD

**Issue by littlezhou** [Intel-bigdata/SSM#1740]

**Comment by PHILO-HE** [comment]
@yaohuan771634

**Comment by PHILO-HE** [comment]
1. Write a shell script in bin/ to distribute the installation package.
2. The package is distributed to the host configured in agents.
3. You can prompt user where to install SSM. Please refer to https://stackoverflow.com/questions/226703/how-do-i-prompt-for-yes-no-cancel-input-in-a-linux-shell-script.
4. You can prompt user to distribute libs for SmartDFSClient use and let user tell which are HDFS nodes. Then the jars starts with "smart" should be copied to these nodes.

**Comment by PHILO-HE** [comment]
Solved by #1874.
