### ISSUE TITLE
File table is not synchronized after set owner, group with dfs client

### ISSUE THREAD

**Issue by gnillor** [Intel-bigdata/SSM#1754]
After I set owner, gourp of a file with different value with hdfs client, the file info of this file in SSM stay the same.

**Comment by qiyuangong** [comment]
This issue can by fixed by updating own and group to file table. But, in file table own and group is stored with ID (oid and gid), while we only get own and group in this place.

**Comment by qiyuangong** [comment]
Already done. Issue closed. :)
