### ISSUE TITLE
Hue error with SSM

### ISSUE THREAD

**Issue by aurorahunter** [Intel-bigdata/SSM#1810]
Hue services fail with SSM enabled:

1.	Either the jars are missing or need to be deployed everywhere (like on Hue hosts too). On EQ Staging Hue hosts are located on different machines than the SSM is deployed on
or
2.	We are missing some Hue specific configuration
or
3. It's a bug and need a debug & fix

To recreate the problem that the BMW users faced, one must go to Hue Web Interface and choose to browse files (the screenshot provided does not show the error, it’s just for clarification how to recreate the steps that will trigger it when SSM is enabled):
(Attached as a .png the error screenshot)
![heu error](https://user-images.githubusercontent.com/26469547/41132566-ba9ba444-6a76-11e8-8f2d-a71e0e944a6e.png)
 
Solution so far:

               Here is a quick update/fix for HUE issue. Please try it in another cluster (We changes too many configurations in that cluster. Please don’t use it currently). 
 
After changing some configurations with Frank, we found that ‘httpfs’ may not work after deploying SSM. This issue leads to HUE issue (HUE’s file browser cannot list files). Because in that test cluster, ‘httpfs’ is configured as HUE’s ‘HDFS web interface role’. Changing this parameter to ‘Namenode’ will solve HUE issue. (Thanks to Frank) 
We also found that copy smart jars to ‘/opt/cloudera/parcels/CDH/lib/hadoop/lib/’ is enough for HUE and HDFS.
 
               We are still working on find root cause of ‘httpfs’ problem. We hope that we can solve it ASAP. As a careful reminder, we changed lots of configurations in that cluster (e.g., disable Kerberos, which make lots of services down). Please don’t change any configuration until we found root cause of ‘httpfs’ problem.

**Comment by qiyuangong** [comment]
Problem solved by changing from httpfs to webhdfs. Issue closed.
