### ISSUE TITLE
Rename log file to distinctive name

### ISSUE THREAD

**Issue by littlezhou** [Intel-bigdata/SSM#1818]
For example, `role-host-user.log`

**Comment by PHILO-HE** [comment]
@yaohuan771634

**Comment by PHILO-HE** [comment]
Currently, SSM's log has same name for ssm server or ssm agent. You need to name the log file with role, host name and user. For a smart agent launched by root on host sr515 as example, its log should be named as agent-sr515-root.log.

**Comment by yaohuan771634** [comment]
ok~

**Comment by PHILO-HE** [comment]
Solved by #1869.
