### ISSUE TITLE
Refine storage utilization page

### ISSUE THREAD

**Issue by littlezhou** [Intel-bigdata/SSM#1950]

**Comment by philo-he** [comment]
![image](https://user-images.githubusercontent.com/13806761/52998510-6c4bfc00-345e-11e9-9308-1fc8a94be999.png)

**Comment by philo-he** [comment]
The button d, h and m respectively represent day, hour, month. It seems that for day and month, the data is wrongly presented.

**Comment by philo-he** [comment]
Fixed by #2050.
