### ISSUE TITLE
documentation on uploading smallfiles to container

### ISSUE THREAD

**Issue by syed72** [Intel-bigdata/SSM#2072]
please provide some documentation to upload smallfiles to container file.
I searched for the same, i could not find it.

Thanks

**Comment by philo-he** [comment]
For small file solution, please click [here ](https://github.com/Intel-bigdata/SSM/blob/trunk/docs/small-file-solution.md)to look into the design doc. Also, you can click [here ](https://github.com/Intel-bigdata/SSM/blob/trunk/docs/small-file-guide.md)to look into the usage guide. Hope these are what you are trying to find. If you have any question, please drop me an email (feilong.he{@}intel.com).
