### ISSUE TITLE
UI issues about new agent information in the Node Info page 

### ISSUE THREAD

**Issue by lipppppp** [Intel-bigdata/SSM#2136]
There are one server and two agents in my SSM cluster. When I started a new agent independently on the worker host, the agent started successfully. But the information displayed about the new agent ID and Status is wrong in the Node Info page. After testing, this new agent can be used normally. So I guess it's a UI issue.
![SSM_UI](https://user-images.githubusercontent.com/32612402/77749999-f9985180-705d-11ea-86e0-2680df89e0ee.png)

**Comment by philo-he** [comment]
I summarized some cases in #2138, please supplement more cases, if any.

**Comment by lipppppp** [comment]
These cases look good. I think one case might be added. If users enable the Server HA and deploy servers on some new nodes, these new servers should be correctly described on the node info page.

**Comment by philo-he** [comment]
#2138 will cover the case you mentioned. Thanks!

**Comment by philo-he** [comment]
Fixed by #2138.
