### ISSUE TITLE
sopport Hadoop 3.0.0-cdh6.0.1

### ISSUE THREAD

**Issue by wangyunpeng666** [Intel-bigdata/SSM#2150]
does the SSM support Hadoop 3.0.0-cdh6.0.1?  I meet some problems when  deployment SSM with Hadoop 3.0.0-cdh6.0.1，such as when I use Standalone service mode, smartserver shut down  suddenly  without  any ERROR when it has been started successfully.
![image](https://user-images.githubusercontent.com/57751906/79936597-72869f80-848a-11ea-91ba-ba0f3c4a24c8.png)
by the way,does this program has webchat group?

**Comment by philo-he** [comment]
We didn't conduct any test on Hadoop 3.0.0-cdh6.0.1. Currently, the support versions are CDH 5.10.1, Hadoop 2.7.3 and Hadoop 3.1.0. I recommend to build SSM for Hadoop 3.1.0 (see [link](https://github.com/Intel-bigdata/SSM/blob/trunk/docs/ssm-deployment-guide.md#for-hadoop-310)) and use the generated SSM dist package in your test with Hadoop 3.0.0-cdh6.0.1.

We have no dedicated developer wechat group, and just built some wechat goups for customers for troubleshooting.

Could you provide any background info, e.g., project purpose?

**Comment by wangyunpeng666** [comment]
> We didn't conduct any test on Hadoop 3.0.0-cdh6.0.1. Currently, the support versions are CDH 5.10.1, Hadoop 2.7.3 and Hadoop 3.1.0. I recommend to build SSM for Hadoop 3.1.0 (see [link](https://github.com/Intel-bigdata/SSM/blob/trunk/docs/ssm-deployment-guide.md#for-hadoop-310)) and use the generated SSM dist package in your test with Hadoop 3.0.0-cdh6.0.1.
> 
> We have no dedicated developer wechat group, and just built some wechat goups for customers for troubleshooting.
> 
> Could you provide any background info, e.g., project purpose?

**Comment by wangyunpeng666** [comment]
Thanks for your help! I am a operation and maintenance engineer in inke. I'm responsible for cluster storage optimization,once  saw this program, I'm very interested and want to apply it to our cluster.But I meet a lot of problems and want to chat with more  friends more conveniently. Also, I hope contribute to this program,Thanks!

**Comment by philo-he** [comment]
Thanks for your interest. I will conduct a simple test on my side with Hadoop 3.0.0-cdh6.0.1. Please send an email to me (feilong.he{at}intel.com) to let me know your email address. I can share some documents to help you figure out SSM basic usage and you can then evaluate whether it is useful in your company envrionment.

**Comment by philo-he** [comment]
I just conducted some simple tests with hadoop-3.0.0-cdh6.0.1. In my test, I used SSM built with `hadoop-3.1` option. This option introduced HDFS (common, client, etc.) 3.1.0 jars to SSM in the building. It looks that there is no issue on hadoop-3.0.0-cdh6.0.1. Certainly, the above runtime issue didn't occur during starting SSM.

In theory, if HDFS has handled the incompatibility issue for 3.1.0 client towards 3.0.0, there should be no issue on SSM side.

Please make sure all configuration is correct and also check HDFS is in service state.
