### ISSUE TITLE
Anonymous user is not supported to login

### ISSUE THREAD

**Issue by philo-he** [Intel-bigdata/SSM#2166]
Zeppelin configuration for allowing anonymous user cannot take effect. A default SSM user (admin) is created and stored in metastore in the first start. Currently, login is inevitable and SSM will authenticate with username/password in database. The document and configuration in zeppelin-site.xml, related to anonymous login is outdated, as well as web-authentication-enable-guide.md.

**Comment by lipppppp** [comment]
When zeppelin.anonymous.allowed is true in the zeppelin-site.xml, you also should change the configuration in the shiro.ini. Enable the “/api/version = anon” and "/** = anon" in the shiro.ini. Then you can login by anonymous user.

**Comment by lipppppp** [comment]
![image](https://user-images.githubusercontent.com/32612402/83831007-136aaa80-a719-11ea-8d05-4430b861cc78.png)

**Comment by philo-he** [comment]
Thanks for your reminding. I have verified it. Closing this issue.
