### ISSUE TITLE
SSM UI don't show "Add Rule" and "Run Action" in the first login.

### ISSUE THREAD

**Issue by lipppppp** [Intel-bigdata/SSM#2172]
There are some problems after adding authentication for smart rest api. SSM UI can't display normally in the first login. After I refresh the page, these problems are gone. 
![image](https://user-images.githubusercontent.com/32612402/84588916-d495cc80-ae5d-11ea-8587-e941dc2372f4.png)

**Comment by philo-he** [comment]
Fixed by #2174. Thanks!
