### ISSUE TITLE
EC/Compact/compress actions lead to lose files temperature.

### ISSUE THREAD

**Issue by lipppppp** [Intel-bigdata/SSM#2181]
For example, we read the file "/test/3.txt" three times. The fid of thi file is 17013.After I read this file three times, the count number and fid are inserted in the table. When ec/compact/compress actions are used, the file fid is changed. But the accessCount table still have the old fid about this file. So the temperature information of this file is lost in some way.
![image](https://user-images.githubusercontent.com/32612402/88008333-a5503a80-cb42-11ea-908a-794dfc630447.png)
![image](https://user-images.githubusercontent.com/32612402/88008598-38897000-cb43-11ea-9ac9-eb5310663638.png)
![image](https://user-images.githubusercontent.com/32612402/88010043-8eabe280-cb46-11ea-906c-b82605a005b1.png)

**Comment by lipppppp** [comment]
Same in the rule, the file "/test/2.txt" fid is 17010. The rule is "file:every 5s | path matches "/test/*" and accessCount(1hour) > 5 | ec -policy XOR-2-1-1024k". After I read this file six times, the count number and fid are inserted in the table. But the file fid is changed to 17015. The hot file page can‘t show the count and the temperature information of this file is lost.
![image](https://user-images.githubusercontent.com/32612402/88010547-b485b700-cb47-11ea-9f2f-42b80f84b653.png)
![image](https://user-images.githubusercontent.com/32612402/88010675-062e4180-cb48-11ea-9a8d-a7fda1503497.png)
![image](https://user-images.githubusercontent.com/32612402/88010702-19411180-cb48-11ea-9bf8-985cbe34a938.png)

**Comment by lipppppp** [comment]
EC/compact/compress related actions will create new files, so I suggest that the fid in these table should be updated after these actions.

**Comment by philo-he** [comment]
Let me try to fix this issue.

**Comment by philo-he** [comment]
Fixed by #2182.

**Comment by philo-he** [comment]
Closing this issue, thanks @lipppppp for reporting this critical issue!
