### ISSUE TITLE
Trigger "at now" doesn't work

### ISSUE THREAD

**Issue by lipppppp** [Intel-bigdata/SSM#2183]
For example, the rule is "file:at now|path matches "/test/*" | cache". When I enable the rule, its state change to FINISHED without doing any actions.

**Comment by lipppppp** [comment]
![image](https://user-images.githubusercontent.com/32612402/88363992-3e39bc80-cdb4-11ea-9896-b6d797afacdb.png)
![image](https://user-images.githubusercontent.com/32612402/88364001-45f96100-cdb4-11ea-84ca-c8b6fe6896ad.png)

**Comment by philo-he** [comment]
Fixed by #2184.
