### ISSUE TITLE
Fail to decompress some kinds of gz files

### ISSUE THREAD

**Issue by lipppppp** [Intel-bigdata/SSM#2192]
I found some problems when I used ssm compression. I write a file which length is 100000000B by ssm action. Then I compress and decompress this file. The decompress action failed.
![image](https://user-images.githubusercontent.com/32612402/92076138-9967c180-edec-11ea-8d40-fe2357c1548d.png)
![image](https://user-images.githubusercontent.com/32612402/92076216-bef4cb00-edec-11ea-8ea2-20ea9e1b0ee4.png)
But when I create a new file which is smaller than the buffer size, the compress and decompress actions succeed. There are two problems.
1.Why compressed file length is larger than itself?
2.What causes decompression failure?
![image](https://user-images.githubusercontent.com/32612402/92076860-e13b1880-eded-11ea-94f0-d359a66b9657.png)

**Comment by philo-he** [comment]
@lipppppp, it seems this feature can work well for file generated by other ways, not by SSM write action.

**Comment by philo-he** [comment]
![image](https://user-images.githubusercontent.com/13806761/92875624-cd219780-f43b-11ea-921b-7a8602b7c2c9.png)
![image](https://user-images.githubusercontent.com/13806761/92875750-ec202980-f43b-11ea-8ac6-3d8e32f5ab9e.png)

**Comment by lipppppp** [comment]
Thanks for @PHILO-HE's support. This issue seems unimportant in the main scenario. We could leave this issue until it's in need.

**Comment by philo-he** [comment]
SSM write file action is just for test use, with random bytes written to that file. For compression codec, the header will be checked, which will report this error if unexpected header is found. Yes, considering compressing a common file works well, we can close this issue and reopen it if there is a strong requirement.
