### ISSUE TITLE
Start time of rules will be reset when server restart

### ISSUE THREAD

**Issue by lipppppp** [Intel-bigdata/SSM#2207]
There is a problem for resetting start time of rule in SSM server starting process. When I submitted a rule like "from 2020-10-28 22:00:00 to 2020-10-28 23:00:00" to start rule at the fixed time, the start time of this rule will be reset if server restart or HA happens. It leads to the rule triggered ahead of fixed time. 
![image](https://user-images.githubusercontent.com/32612402/97250224-7aac0700-1840-11eb-9b88-407c108bdf8f.png)
![image](https://user-images.githubusercontent.com/32612402/97250467-fa39d600-1840-11eb-93d0-61a1d24cdb72.png)

**Comment by philo-he** [comment]
With your proposed patch in #2202, will this issue still occur?

**Comment by lipppppp** [comment]
#2202 solved this problem. And other functions are not affected.
