### ISSUE TITLE
SmartClient retry to connect standby server in HA mode

### ISSUE THREAD

**Issue by lipppppp** [Intel-bigdata/SSM#2228]
The SmartClient will retry to connnect standby server when the value of smart.server.rpc.address is "ssm1:7042, ssm2:7042" and active server is ssm2. Although this read action finally successed, it still should wait for a long time. 
SmartClient#reportFileAccessEvent will get first server to report access event, and the serverQue follow the order in the value. So, this problem could be solved if make active server to the first of this queue. But I don't know how to get active server hostname in client side. Look forward to your suggestions.
![image](https://user-images.githubusercontent.com/32612402/106104640-af03cc00-617d-11eb-8a9d-2160e423db03.png)

**Comment by philo-he** [comment]
I worked out a patch. See #2229. A local tmp file is used to record newly found active server and retry mechanism is still kept.

**Comment by lipppppp** [comment]
Thanks. I will test this patch later.

**Comment by lipppppp** [comment]
This problem solved by #2229. Thanks for @PHILO-HE's support.
