### ISSUE TITLE
Implement RPC call for getting ActionInfo

### ISSUE THREAD

**Issue by littlezhou** [Intel-bigdata/SSM#274]

**Comment by littlezhou** [comment]
/**
   * Get action info about certain action denoted by actionID.
   * @param actionID
   * @return
   * @throws IOException
   */
  ActionInfo getActionInfo(long actionID) throws IOException;


  /**
   * List info of newly generated actions.
   * @param maxNumActions max number of action info to return
   * @return
   * @throws IOException
   */
  List<ActionInfo> listActionInfoOfLastActions(int maxNumActions)
      throws IOException;

**Comment by drankye** [comment]
This was already done.
