### ISSUE TITLE
[SSM] NN checkpoint plugin mechanism

### ISSUE THREAD

**Issue by littlezhou** [Intel-bigdata/SSM#39]

**Comment by manuzhang** [comment]
This can be achieved through [Hadoop Metrics2](https://hadoop.apache.org/docs/r3.0.0-alpha2/api/org/apache/hadoop/metrics2/package-frame.html) and its [pluggable sink](https://hadoop.apache.org/docs/r3.0.0-alpha2/api/org/apache/hadoop/metrics2/MetricsSink.html). The support is added through #146
