### ISSUE TITLE
Migrate metastore to mysql

### ISSUE THREAD

**Issue by qiyuangong** [Intel-bigdata/SSM#399]
- [x] Add Mysql support.
- [x] mysql in docker.
- [x] Better support for mysql conf.
- [x] Test and migrate.

**Comment by qiyuangong** [comment]
**Install mysql images**
```
docker pull mysql
```

**Launch a docker container with mysql**
```
docker run -p 3306:3306 --name test-mysql -e MYSQL_ROOT_PASSWORD=root -d mysql:latest
```

**Comment by manuzhang** [comment]
mysql is GPL license, which is incompatible with Apache License. An alternative is https://github.com/datanucleus/datanucleus-rdbms, which is [used by hive-metastore](https://github.com/apache/hive/blob/master/metastore/pom.xml#L116)

**Comment by qiyuangong** [comment]
Already Finished. 
@manuzhang  GPL license issue will be addressed later.
