### ISSUE TITLE
Reduce Connection during Insert

### ISSUE THREAD

**Issue by qiyuangong** [Intel-bigdata/SSM#502]
Due to the limitation of jdbctemplate, currently each insertion will require a connection, and release it after insertion. It is not friendly to Metastore, and may exceed the `max connection` if many large batch insertions are used at the same time.

**Comment by duzhen1996** [comment]
SimpleJdbcTemplate provides a function for batch inserting.

**Comment by duzhen1996** [comment]
SimpleJdbcTemplate provides a function for batch insert, called batchUpdate. We can convert the objects to maps as a  parameter of this function.
This page describes the details of this function：https://docs.spring.io/spring/docs/2.5.x/javadoc-api/org/springframework/jdbc/core/simple/SimpleJdbcInsert.html#executeBatch(java.util.Map[])

**Comment by qiyuangong** [comment]
Nice. Please connect your pull request with this issue.

**Comment by qiyuangong** [comment]
Already done. Thanks @duzhen1996
