### ISSUE TITLE
Incorrect override function `equals`

### ISSUE THREAD

**Issue by huafengw** [Intel-bigdata/SSM#591]
I found many classes' `equals` function is not correct.
 For example, in `FileInfo` the function signature is `public boolean equals(FileInfo fileInfo)`, which is wrong. The right function signature should be `public boolean equals(Object other)`.

Also, when overriding `equals`, the `hashCode` function should also be overridden. Please refer https://stackoverflow.com/a/17027845

**Comment by huafengw** [comment]
`org.smartdata.server.engine.cmdlet.CmdletDescriptor`
`org.smartdata.model.RuleInfo`
`org.smartdata.rule.objects.Property`
`org.smartdata.rule.objects.PropertyRealParas`

**Comment by littlezhou** [comment]
Done!
