### ISSUE TITLE
Smart server fail to run as a daemon when --daemon option is used 

### ISSUE THREAD

**Issue by ChenSammi** [Intel-bigdata/SSM#648]
Command used: 
 bin/start-smart.sh --config ./conf --daemon

After run the above command, the smart server started with following piece of error logs. And smart server didn't close the console output to be a daemon process.

Please browse to http://0.0.0.0:7045 to see the web UI
Jul 10, 2017 5:30:10 PM com.sun.jersey.server.impl.application.WebApplicationImpl _initiate
INFO: Initiating Jersey application, version 'Jersey: 1.9 09/02/2011 11:17 AM'
Jul 10, 2017 5:30:10 PM com.sun.jersey.spi.inject.Errors processErrorMessages
WARNING: The following warnings have been detected with resource and/or provider classes:
  WARNING: A sub-resource method, public javax.ws.rs.core.Response org.smartdata.server.rest.ConfRestApi.conf(), with URI template, "", is treated as a resource method
Jul 10, 2017 5:30:10 PM com.sun.jersey.server.impl.application.WebApplicationImpl _initiate
INFO: Initiating Jersey application, version 'Jersey: 1.9 09/02/2011 11:17 AM'
Jul 10, 2017 5:30:11 PM com.sun.jersey.spi.inject.Errors processErrorMessages
WARNING: The following warnings have been detected with resource and/or provider classes:
  WARNING: A sub-resource method, public javax.ws.rs.core.Response org.apache.zeppelin.rest.NotebookRestApi.createNote(java.lang.String) throws java.io.IOException, with URI template, "/", is treated as a resource method
  WARNING: A sub-resource method, public javax.ws.rs.core.Response org.apache.zeppelin.rest.NotebookRestApi.getNoteList() throws java.io.IOException, with URI template, "/", is treated as a resource method
  WARNING: A HTTP GET method, public javax.ws.rs.core.Response org.apache.zeppelin.rest.CredentialRestApi.getCredentials(java.lang.String) throws java.io.IOException,java.lang.IllegalArgumentException, should not consume any entity.
  WARNING: A HTTP GET method, public javax.ws.rs.core.Response org.apache.zeppelin.rest.InterpreterRestApi.listInterpreter(java.lang.String), should not consume any entity.

**Comment by littlezhou** [comment]
Solved in issue #649
