### ISSUE TITLE
The error message of UI action carries no meaning 

### ISSUE THREAD

**Issue by ChenSammi** [Intel-bigdata/SSM#654]
Try "read" action with an file nonexistent, the error message says nothing about the file is actually not exist. 

Create Time | 2017-07-10 19:05:52
Finish Time | 2017-07-10 19:05:52
Running Time | 2 ms
Result |  
Log | Action starts at Mon Jul 10 19:05:52 PDT 2017 : Read null\n

**Comment by huafengw** [comment]
Done
