### ISSUE TITLE
File access information lost after Smart server restart

### ISSUE THREAD

**Issue by ChenSammi** [Intel-bigdata/SSM#656]
1. read file A through action "read" on UI
2. switch UI to hot files list, there is file A 
3. restart smart server
4. goto UI hot files list, the list is empty

**Comment by huafengw** [comment]
It's related to issue #637

**Comment by ChenSammi** [comment]
OK, good to know. Once #637 is fixed, you can close this one too.

**Comment by huafengw** [comment]
Resolved in #670
