### ISSUE TITLE
Access account accuracy 

### ISSUE THREAD

**Issue by ChenSammi** [Intel-bigdata/SSM#700]
1. run TestDFSIO with  write operation to write 10 fils
bin/hadoop jar ./share/hadoop/mapreduce/hadoop-mapreduce-client-jobclient-2.6.0-cdh5.10.1-tests.jar TestDFSIO -write -nrFiles 10 -size 10mb

2. 11 file access reports are received. 
Access:/benchmarks/TestDFSIO/io_control/in_file_test_io_0
Access:/benchmarks/TestDFSIO/io_control/in_file_test_io_1
Access:/benchmarks/TestDFSIO/io_control/in_file_test_io_2
Access:/benchmarks/TestDFSIO/io_control/in_file_test_io_3
Access:/benchmarks/TestDFSIO/io_control/in_file_test_io_4
Access:/benchmarks/TestDFSIO/io_control/in_file_test_io_5
Access:/benchmarks/TestDFSIO/io_control/in_file_test_io_6
Access:/benchmarks/TestDFSIO/io_control/in_file_test_io_7
Access:/benchmarks/TestDFSIO/io_control/in_file_test_io_8
Access:/benchmarks/TestDFSIO/io_control/in_file_test_io_9
Access:/benchmarks/TestDFSIO/io_write/part-00000

3. On UI hot files table, only 5 files are listed. 
4. Actually when I press the "Account" column to sort the files, it sometimes will jump from 5 files to 7 files. 

I'm not sure if it's only a UI issue. Is there anyway to check if the file access report stored in DB is correct?

**Comment by huafengw** [comment]
Thanks for reporting this one, can you help to verify the http response of api `hotfiles` to see whether it's a UI or backend issue?

**Comment by ChenSammi** [comment]
[{"fid":17015,"path":"/benchmarks/TestDFSIO/io_control/in_file_test_io_8","accessCount":1},{"fid":17012,"path":"/benchmarks/TestDFSIO/io_control/in_file_test_io_5","accessCount":1},{"fid":17011,"path":"/benchmarks/TestDFSIO/io_control/in_file_test_io_4","accessCount":1},{"fid":17010,"path":"/benchmarks/TestDFSIO/io_control/in_file_test_io_3","accessCount":1},{"fid":17009,"path":"/benchmarks/TestDFSIO/io_control/in_file_test_io_2","accessCount":1},{"fid":17008,"path":"/benchmarks/TestDFSIO/io_control/in_file_test_io_1","accessCount":1},{"fid":17016,"path":"/benchmarks/TestDFSIO/io_control/in_file_test_io_9","accessCount":1}]

Seems UI shows what backend returns.

**Comment by ChenSammi** [comment]
I did the same TestDFSIO read 10 files test, 3 times. 
After the 3 run, the hot files shows 10 file, each with 3 account.  But it missing other 11 files, each one has 1 access account.  From this observation, I tend to believe the issue exists in the SQL statement to read out the hot files, not the SQL statement insert access count data into DB.

This issue can be easily reproduced using SmartFileSystem to enable the file access report transparently when TestDFSIO is running.  I documented SmartFileSystem deploy guide in SmartFileSystem.java comments.  

Hi guys,  we need to close this issue before we handle over the first SSM package to ADAS tomorrow. 
I will also try to debug the issue in the meantime.

**Comment by ChenSammi** [comment]
I tried to remove the "ORDER BY %s DESC LIMIT %s" in the getHotFiles SQL statement. After that, hot files table shows as excepted.

After dig deeper into the results returned by the SQL statement, I find a lot access count '0' records. 
Why there are "0" value records?  Can it be the root cause?  

2017-07-13 17:57:05,811 INFO org.smartdata.metastore.dao.AccessCountDao.getHotFiles 125: Hot files:{17329=1, 17320=1, 17313=1, 17312=1, 17315=1, 17314=1, 17317=1, 17319=2, 17318=6, 17033=4, 17306=1, 17032=4, 17307=1, 17035=4, 17034=4, 17037=4, 17310=1, 17036=4, 17311=1, 17308=1, 17038=4, 17309=1, 17298=1, 17029=4, 17031=4, 17030=4, 17289=1, 17288=2, 17283=1, 17282=1, 17281=1, 17280=1, 17287=10, 17286=1, 17284=1, 17150=0, 17151=0, 17148=0, 17149=0, 17202=0, 17213=1, 17215=1, 17214=1, 17184=0, 17185=0, 17186=0, 17187=0, 17188=0, 17190=0, 17191=0, 17192=0, 17193=0, 17171=0, 17179=0, 17183=0, 17182=0, 17181=0, 17180=0, 17154=0, 17155=0, 17152=0, 17153=0, 17159=0, 17156=0, 17157=0, 17162=0, 17160=0, 17161=0, 17267=1, 17277=1, 17276=1, 17279=1, 17278=1, 17275=1, 17252=1, 17253=1, 17255=1, 17248=1, 17249=1, 17250=1, 17251=1, 17256=10, 17257=2, 17258=1, 17236=1, 17247=1, 17246=1, 17245=1, 17244=1, 17222=1, 17220=1, 17221=1, 17218=1, 17219=1, 17216=1, 17217=1, 17226=2, 17227=1, 17224=1, 17225=9}

**Comment by huafengw** [comment]
I found the root cause, which turns out not a bug.

For example, when you launch a map reduce job to read 50 files, the job will create some temporarily files and read them for multiple times. After the job is finished, these temporarily files will be deleted. Then when querying latest 50 hot files, these temporarily files' access history will also be taken into account, but eventually be filtered out because they no longer exist. So the dashboard will show less than 50 files.

**Comment by ChenSammi** [comment]
Great! 
I understand the process now. But it's logic doesn't match end user's expectation.  Can we filter out these no longer existing files and account value 0 files first, then get the highest 50 access count files as the output?
