### ISSUE TITLE
File access report optimization for YARN

### ISSUE THREAD

**Issue by ChenSammi** [Intel-bigdata/SSM#702]
Run a TestDFSIO with YARN, a lot of YARN temporary files and managements files are created and accessed during the whole process.
   
I'm thinking of improve it,  filter out all the files under /tmp/hadoop-yarn, so there will be less traffic between the SmartFileSystem, SmartDFSClient and SmartServer. 
Do you guys see any inappropriate of doing this?  

event type:UNLINK, path:/benchmarks/TestDFSIO/io_control
event type:CREATE, path:/benchmarks/TestDFSIO/io_control
event type:CREATE, path:/benchmarks/TestDFSIO/io_control/in_file_test_io_0
InotifyFetchAndApplyTask run at Wed Jul 12 16:31:42 PDT 2017
InotifyFetchAndApplyTask run at Wed Jul 12 16:31:42 PDT 2017
event type:CLOSE, path:/benchmarks/TestDFSIO/io_control/in_file_test_io_0
event type:CREATE, path:/benchmarks/TestDFSIO/io_control/in_file_test_io_1
event type:CLOSE, path:/benchmarks/TestDFSIO/io_control/in_file_test_io_1
event type:CREATE, path:/benchmarks/TestDFSIO/io_control/in_file_test_io_2
event type:CLOSE, path:/benchmarks/TestDFSIO/io_control/in_file_test_io_2
event type:CREATE, path:/benchmarks/TestDFSIO/io_control/in_file_test_io_3
event type:CLOSE, path:/benchmarks/TestDFSIO/io_control/in_file_test_io_3
event type:CREATE, path:/benchmarks/TestDFSIO/io_control/in_file_test_io_4
event type:CLOSE, path:/benchmarks/TestDFSIO/io_control/in_file_test_io_4
event type:CREATE, path:/benchmarks/TestDFSIO/io_control/in_file_test_io_5
event type:CLOSE, path:/benchmarks/TestDFSIO/io_control/in_file_test_io_5
event type:CREATE, path:/benchmarks/TestDFSIO/io_control/in_file_test_io_6
event type:CLOSE, path:/benchmarks/TestDFSIO/io_control/in_file_test_io_6
event type:CREATE, path:/benchmarks/TestDFSIO/io_control/in_file_test_io_7
event type:CLOSE, path:/benchmarks/TestDFSIO/io_control/in_file_test_io_7
event type:CREATE, path:/benchmarks/TestDFSIO/io_control/in_file_test_io_8
event type:CLOSE, path:/benchmarks/TestDFSIO/io_control/in_file_test_io_8
event type:CREATE, path:/benchmarks/TestDFSIO/io_control/in_file_test_io_9
event type:CLOSE, path:/benchmarks/TestDFSIO/io_control/in_file_test_io_9
event type:UNLINK, path:/benchmarks/TestDFSIO/io_read
event type:CREATE, path:/tmp
event type:CREATE, path:/tmp/hadoop-yarn
event type:CREATE, path:/tmp/hadoop-yarn/staging
event type:CREATE, path:/tmp/hadoop-yarn/staging/drankye
event type:CREATE, path:/tmp/hadoop-yarn/staging/drankye/.staging
event type:CREATE, path:/tmp/hadoop-yarn/staging/drankye/.staging/job_1499902233112_0001
event type:METADATA, path:/tmp/hadoop-yarn/staging/drankye/.staging/job_1499902233112_0001
event type:CREATE, path:/tmp/hadoop-yarn/staging/drankye/.staging/job_1499902233112_0001/job.jar
event type:CLOSE, path:/tmp/hadoop-yarn/staging/drankye/.staging/job_1499902233112_0001/job.jar
event type:METADATA, path:/tmp/hadoop-yarn/staging/drankye/.staging/job_1499902233112_0001/job.jar
event type:METADATA, path:/tmp/hadoop-yarn/staging/drankye/.staging/job_1499902233112_0001/job.jar
event type:CREATE, path:/tmp/hadoop-yarn/staging/drankye/.staging/job_1499902233112_0001/job.split
event type:METADATA, path:/tmp/hadoop-yarn/staging/drankye/.staging/job_1499902233112_0001/job.split
event type:METADATA, path:/tmp/hadoop-yarn/staging/drankye/.staging/job_1499902233112_0001/job.split
event type:CLOSE, path:/tmp/hadoop-yarn/staging/drankye/.staging/job_1499902233112_0001/job.split
event type:CREATE, path:/tmp/hadoop-yarn/staging/drankye/.staging/job_1499902233112_0001/job.splitmetainfo
event type:METADATA, path:/tmp/hadoop-yarn/staging/drankye/.staging/job_1499902233112_0001/job.splitmetainfo
event type:CLOSE, path:/tmp/hadoop-yarn/staging/drankye/.staging/job_1499902233112_0001/job.splitmetainfo
event type:CREATE, path:/tmp/hadoop-yarn/staging/drankye/.staging/job_1499902233112_0001/job.xml
event type:METADATA, path:/tmp/hadoop-yarn/staging/drankye/.staging/job_1499902233112_0001/job.xml
event type:CLOSE, path:/tmp/hadoop-yarn/staging/drankye/.staging/job_1499902233112_0001/job.xml
Access:/tmp/hadoop-yarn/staging/drankye/.staging/job_1499902233112_0001/job.jar
InotifyFetchAndApplyTask run at Wed Jul 12 16:31:45 PDT 2017
InotifyFetchAndApplyTask run at Wed Jul 12 16:31:45 PDT 2017
Access:/tmp/hadoop-yarn/staging/drankye/.staging/job_1499902233112_0001/job.splitmetainfo
Access:/tmp/hadoop-yarn/staging/drankye/.staging/job_1499902233112_0001/job.split
InotifyFetchAndApplyTask run at Wed Jul 12 16:31:46 PDT 2017
Access:/tmp/hadoop-yarn/staging/drankye/.staging/job_1499902233112_0001/job.xml
event type:CREATE, path:/tmp/hadoop-yarn/staging/history
event type:CREATE, path:/tmp/hadoop-yarn/staging/history/done_intermediate
event type:METADATA, path:/tmp/hadoop-yarn/staging/history/done_intermediate
event type:CREATE, path:/tmp/hadoop-yarn/staging/history/done_intermediate/drankye
event type:METADATA, path:/tmp/hadoop-yarn/staging/history/done_intermediate/drankye
InotifyFetchAndApplyTask run at Wed Jul 12 16:31:48 PDT 2017
InotifyFetchAndApplyTask run at Wed Jul 12 16:31:48 PDT 2017
Access:/tmp/hadoop-yarn/staging/drankye/.staging/job_1499902233112_0001/job.splitmetainfo
event type:CREATE, path:/tmp/hadoop-yarn/staging/drankye/.staging/job_1499902233112_0001/job_1499902233112_0001_1.jhist
event type:CREATE, path:/benchmarks/TestDFSIO/io_read
event type:CREATE, path:/benchmarks/TestDFSIO/io_read/_temporary
event type:CREATE, path:/benchmarks/TestDFSIO/io_read/_temporary/1
event type:CREATE, path:/tmp/hadoop-yarn/staging/drankye/.staging/job_1499902233112_0001/job_1499902233112_0001_1_conf.xml
InotifyFetchAndApplyTask run at Wed Jul 12 16:31:49 PDT 2017
InotifyFetchAndApplyTask run at Wed Jul 12 16:31:49 PDT 2017
InotifyFetchAndApplyTask run at Wed Jul 12 16:31:49 PDT 2017
event type:CLOSE, path:/tmp/hadoop-yarn/staging/drankye/.staging/job_1499902233112_0001/job_1499902233112_0001_1_conf.xml
event type:CREATE, path:/tmp/hadoop-yarn/staging/drankye/.staging/job_1499902233112_0001/job_1499902233112_0001.summary
event type:CLOSE, path:/tmp/hadoop-yarn/staging/drankye/.staging/job_1499902233112_0001/job_1499902233112_0001.summary
Access:/tmp/hadoop-yarn/staging/drankye/.staging/job_1499902233112_0001/job.split
InotifyFetchAndApplyTask run at Wed Jul 12 16:31:54 PDT 2017
Access:/benchmarks/TestDFSIO/io_control/in_file_test_io_0
InotifyFetchAndApplyTask run at Wed Jul 12 16:31:54 PDT 2017
Access:/benchmarks/TestDFSIO/io_data/test_io_0
Access:/tmp/hadoop-yarn/staging/drankye/.staging/job_1499902233112_0001/job.split
InotifyFetchAndApplyTask run at Wed Jul 12 16:31:55 PDT 2017
Access:/benchmarks/TestDFSIO/io_control/in_file_test_io_1
InotifyFetchAndApplyTask run at Wed Jul 12 16:31:55 PDT 2017
Access:/benchmarks/TestDFSIO/io_data/test_io_1
Access:/tmp/hadoop-yarn/staging/drankye/.staging/job_1499902233112_0001/job.split
InotifyFetchAndApplyTask run at Wed Jul 12 16:31:56 PDT 2017
Access:/benchmarks/TestDFSIO/io_control/in_file_test_io_2
InotifyFetchAndApplyTask run at Wed Jul 12 16:31:56 PDT 2017
InotifyFetchAndApplyTask run at Wed Jul 12 16:31:56 PDT 2017
Access:/benchmarks/TestDFSIO/io_data/test_io_2
Access:/tmp/hadoop-yarn/staging/drankye/.staging/job_1499902233112_0001/job.split
Access:/benchmarks/TestDFSIO/io_control/in_file_test_io_3
Access:/benchmarks/TestDFSIO/io_data/test_io_3
Access:/tmp/hadoop-yarn/staging/drankye/.staging/job_1499902233112_0001/job.split
Access:/tmp/hadoop-yarn/staging/drankye/.staging/job_1499902233112_0001/job.split
Access:/benchmarks/TestDFSIO/io_control/in_file_test_io_4
Access:/benchmarks/TestDFSIO/io_control/in_file_test_io_5
Access:/benchmarks/TestDFSIO/io_data/test_io_4
Access:/benchmarks/TestDFSIO/io_data/test_io_5
Access:/tmp/hadoop-yarn/staging/drankye/.staging/job_1499902233112_0001/job.split
Access:/benchmarks/TestDFSIO/io_control/in_file_test_io_6
Access:/benchmarks/TestDFSIO/io_data/test_io_6
Access:/tmp/hadoop-yarn/staging/drankye/.staging/job_1499902233112_0001/job.split
Access:/benchmarks/TestDFSIO/io_control/in_file_test_io_7
Access:/benchmarks/TestDFSIO/io_data/test_io_7
Access:/tmp/hadoop-yarn/staging/drankye/.staging/job_1499902233112_0001/job.split
Access:/benchmarks/TestDFSIO/io_control/in_file_test_io_8
Access:/benchmarks/TestDFSIO/io_data/test_io_8
Access:/tmp/hadoop-yarn/staging/drankye/.staging/job_1499902233112_0001/job.split
Access:/benchmarks/TestDFSIO/io_control/in_file_test_io_9
Access:/benchmarks/TestDFSIO/io_data/test_io_9
event type:CREATE, path:/benchmarks/TestDFSIO/io_read/_temporary/1/_temporary
event type:CREATE, path:/benchmarks/TestDFSIO/io_read/_temporary/1/_temporary/attempt_1499902233112_0001_r_000000_0
event type:CREATE, path:/benchmarks/TestDFSIO/io_read/_temporary/1/_temporary/attempt_1499902233112_0001_r_000000_0/part-00000
Access:/tmp/hadoop-yarn/staging/drankye/.staging/job_1499902233112_0001/job_1499902233112_0001_1.jhist
Access:/tmp/hadoop-yarn/staging/drankye/.staging/job_1499902233112_0001/job_1499902233112_0001_1_conf.xml
event type:CLOSE, path:/benchmarks/TestDFSIO/io_read/_temporary/1/_temporary/attempt_1499902233112_0001_r_000000_0/part-00000
event type:RENAME, src path:/benchmarks/TestDFSIO/io_read/_temporary/1/_temporary/attempt_1499902233112_0001_r_000000_0, dest path:/benchmarks/TestDFSIO/io_read/_temporary/1/task_1499902233112_0001_r_000000
event type:CREATE, path:/tmp/hadoop-yarn/staging/drankye/.staging/job_1499902233112_0001/COMMIT_STARTED
event type:CLOSE, path:/tmp/hadoop-yarn/staging/drankye/.staging/job_1499902233112_0001/COMMIT_STARTED
event type:RENAME, src path:/benchmarks/TestDFSIO/io_read/_temporary/1/task_1499902233112_0001_r_000000/part-00000, dest path:/benchmarks/TestDFSIO/io_read/part-00000
event type:UNLINK, path:/benchmarks/TestDFSIO/io_read/_temporary
event type:CREATE, path:/benchmarks/TestDFSIO/io_read/_SUCCESS
event type:CLOSE, path:/benchmarks/TestDFSIO/io_read/_SUCCESS
event type:CREATE, path:/tmp/hadoop-yarn/staging/drankye/.staging/job_1499902233112_0001/COMMIT_SUCCESS
event type:CLOSE, path:/tmp/hadoop-yarn/staging/drankye/.staging/job_1499902233112_0001/COMMIT_SUCCESS
event type:CLOSE, path:/tmp/hadoop-yarn/staging/drankye/.staging/job_1499902233112_0001/job_1499902233112_0001_1.jhist
event type:CREATE, path:/tmp/hadoop-yarn/staging/history/done_intermediate/drankye/job_1499902233112_0001.summary_tmp
event type:CLOSE, path:/tmp/hadoop-yarn/staging/history/done_intermediate/drankye/job_1499902233112_0001.summary_tmp
event type:METADATA, path:/tmp/hadoop-yarn/staging/history/done_intermediate/drankye/job_1499902233112_0001.summary_tmp
	event type:CREATE, path:/tmp/hadoop-yarn/staging/history/done_intermediate/drankye/job_1499902233112_0001-1499902303823-drankye-hadoop%2Dmapreduce%2Dclient%2Djobclient%2D2.6.0%2Dcdh5.10.1%2D-1499902325166-10-1-SUCCEEDED-root.drankye-1499902309597.jhist_tmp
event type:CLOSE, path:/tmp/hadoop-yarn/staging/history/done_intermediate/drankye/job_1499902233112_0001-1499902303823-drankye-hadoop%2Dmapreduce%2Dclient%2Djobclient%2D2.6.0%2Dcdh5.10.1%2D-1499902325166-10-1-SUCCEEDED-root.drankye-1499902309597.jhist_tmp
event type:METADATA, path:/tmp/hadoop-yarn/staging/history/done_intermediate/drankye/job_1499902233112_0001-1499902303823-drankye-hadoop%2Dmapreduce%2Dclient%2Djobclient%2D2.6.0%2Dcdh5.10.1%2D-1499902325166-10-1-SUCCEEDED-root.drankye-1499902309597.jhist_tmp
event type:CREATE, path:/tmp/hadoop-yarn/staging/history/done_intermediate/drankye/job_1499902233112_0001_conf.xml_tmp
event type:CLOSE, path:/tmp/hadoop-yarn/staging/history/done_intermediate/drankye/job_1499902233112_0001_conf.xml_tmp
event type:METADATA, path:/tmp/hadoop-yarn/staging/history/done_intermediate/drankye/job_1499902233112_0001_conf.xml_tmp
event type:RENAME, src path:/tmp/hadoop-yarn/staging/history/done_intermediate/drankye/job_1499902233112_0001.summary_tmp, dest path:/tmp/hadoop-yarn/staging/history/done_intermediate/drankye/job_1499902233112_0001.summary
event type:RENAME, src path:/tmp/hadoop-yarn/staging/history/done_intermediate/drankye/job_1499902233112_0001_conf.xml_tmp, dest path:/tmp/hadoop-yarn/staging/history/done_intermediate/drankye/job_1499902233112_0001_conf.xml
event type:RENAME, src path:/tmp/hadoop-yarn/staging/history/done_intermediate/drankye/job_1499902233112_0001-1499902303823-drankye-hadoop%2Dmapreduce%2Dclient%2Djobclient%2D2.6.0%2Dcdh5.10.1%2D-1499902325166-10-1-SUCCEEDED-root.drankye-1499902309597.jhist_tmp, dest path:/tmp/hadoop-yarn/staging/history/done_intermediate/drankye/job_1499902233112_0001-1499902303823-drankye-hadoop%2Dmapreduce%2Dclient%2Djobclient%2D2.6.0%2Dcdh5.10.1%2D-1499902325166-10-1-SUCCEEDED-root.drankye-1499902309597.jhist
event type:UNLINK, path:/tmp/hadoop-yarn/staging/drankye/.staging/job_1499902233112_0001
Access:/benchmarks/TestDFSIO/io_read/part-00000

**Comment by littlezhou** [comment]
Good ideal, we can make it a general feature to discard access events for certain files. We may also need a feature to ignore namespace changes under certain dirs, for your case "/tmp".

**Comment by littlezhou** [comment]
Solved.
