### ISSUE TITLE
Start smart server without --daemon option will fail to start the server

### ISSUE THREAD

**Issue by ChenSammi** [Intel-bigdata/SSM#721]
bin/start-smart.sh --config ./conf
SMART_CONF_DIR=./conf
Starting SmartServer ...
Permission denied (publickey,password,keyboard-interactive)

It's on Mac. No sure if it will have the same effect on Linux. 

Maybe we can consider make the  --daemon as a default option since generally services are running as daemons.

**Comment by littlezhou** [comment]
the error was caused by that the script can not ssh to localhost without input password, please recheck it.

**Comment by littlezhou** [comment]
Solved.
