### ISSUE TITLE
'start-smart.sh -format' should not start the smart daemon 

### ISSUE THREAD

**Issue by ChenSammi** [Intel-bigdata/SSM#748]
This script merely format the DB, create all the tables. If it requires a smart daemon in the process, it should stop the daemon at the end of the script

**Comment by ChenSammi** [comment]
Add one more condition for this case: format failed.

**Comment by littlezhou** [comment]
it stops automatically when format operation ends, so no need to stop the daemon at the end of the script

**Comment by littlezhou** [comment]
Solved!
