### ISSUE TITLE
Define interface for the self-defined Mover

### ISSUE THREAD

**Issue by timmyyao** [Intel-bigdata/SSM#78]
- [x] MoverPool : manage all mover actions
- [x] MoverStatus : define information of the status needed and define corresponding interface
- [x] UT

**Comment by timmyyao** [comment]
- [ ] MoverPool : manage all mover actions
- [ ] MoverStatus : define information of the status needed and define corresponding interface
- [ ] UT

**Comment by littlezhou** [comment]
Done!
