### ISSUE TITLE
It takes too long to fetch  the namespace when SSM server starts

### ISSUE THREAD

**Issue by ChenSammi** [Intel-bigdata/SSM#935]
260s,  2k+ directory, 700+ node

**Comment by huafengw** [comment]
Currently, after each fetch of a directory, the thread will sleep 100 ms.

Here is the configuration 

https://github.com/Intel-bigdata/SSM/blob/abe8212e6f178fb57edeafdbcda45e0e2938486e/smart-hadoop-support/smart-hadoop/src/main/java/org/smartdata/hdfs/metric/fetcher/NamespaceFetcher.java#L40

**Comment by ChenSammi** [comment]
You' are right. After change the sleep time from 100 ms, it only requires  3s to finish the fetching process. 

I would suggest we improve the sleep logic, remove the sleep is also a choice.

**Comment by drankye** [comment]
So far using the configuration to tune the namespace sync up speed is good and reliable. We have to avoid big impact to NN when possible. Close this now and open new for related issues.
