### ISSUE TITLE
Changing script names to use "ssm" instead of "smart"

### ISSUE THREAD

**Issue by drankye** [Intel-bigdata/SSM#938]
How about changing our script names some bit? "smart" here isn't good, instead "ssm" might be better.
Note this doesn't mean we need to convert back to ssm for other instances across the codes.
common.sh*
functions.sh*
smart*
smart-init.sh*
start-smart.sh*
stop-smart.sh*

@littlezhou Agree? Thanks.

**Comment by littlezhou** [comment]
Ok for me, I'll change it. Thanks!

**Comment by littlezhou** [comment]
Done!
